# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shanweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dgjdv7o2caeog7mregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7102830c28d549baadf561262e201be8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f2ecb3195924645adeee07d86cefbac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dgjdv7o2caeog7mregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7102830c28d549baadf561262e201be8 }}/devguidebackendapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shanweb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_aef12f18dddc48d89c73760078e6b735 }}
        images: 'dgjdv7o2caeog7mregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7102830c28d549baadf561262e201be8 }}/devguidebackendapi:${{ github.sha }}'